### ISSUE TITLE
No longer sorted by number of stars

### ISSUE THREAD

**Issue by hectorv** [vitalets/github-trending-repos#141]
Repos used to be sorted by number of stars. Unfortunately, that's no longer the case:

<img width="1187" alt="Re___vitalets_github-trending-repos__New_weekly_trending_repos_in_Python___11__-_hector_duolingo_com_-_Duolingo_Mail" src="https://user-images.githubusercontent.com/85069/65334826-3b1ce100-db91-11e9-8fe8-86b9b9155c4c.png">

**Comment by vitalets** [comment]
I've checked original [GitHub trending page ](https://github.com/trending/python?since=daily)- it also does not sort repos by stars now. Maybe their sorting algorithm considers other criterias..  

Here the example for Python:
![image](https://user-images.githubusercontent.com/1473072/65541441-03f25b00-df16-11e9-9153-8c3050597dc2.png)
