### ISSUE TITLE
Mentioned contributors get automatically added to the circulation list by Github

### ISSUE THREAD

**Issue by dominicsayers** [vitalets/github-trending-repos#48]
Not sure if this is intentional or not, but because I was @-mentioned in the description of a trending repo, I got added to the circulation list for that category https://github.com/vitalets/github-trending-repos/issues/10

Here's the repo that mentioned me: https://github.com/egulias/EmailValidator

Just thought I'd let you know in case this was an unintended consequence.

**Comment by vitalets** [comment]
Hi @dominicsayers !
Thanks for informing about that. It's interesting case - mentioning someone in repo description. Here I think there is no problem because mentioned user can just unsubscribe from issue if it does not need trending repos updates.
In common I think it's not good to mention someone in description because many services can automatically pull preview of repo via GitHub API and mentioned user can get mentioned in several places else =)
